id = "shadow-energy"
name = "Shadow Energy"
version = "0.1.0"
schema_version = 1
authors = ["Yassine Ait Rahou <yassine.aitrahou0@gmail.com>"]
description = "A dark blue theme for the Zed text editor inspired by the vibrant energy of a dark blue show."
repository = "https://github.com/averrois/shadow-energy-zed"
